### ISSUE TITLE
Pipx on Ubuntu images

### ISSUE THREAD

**Issue by klinga** [phette23/marcgreppy#2]
FYI,
GitHub Actions runner images include pipx, which means the [package manager is available on Ubuntu out of the box](https://github.com/actions/runner-images?tab=readme-ov-file#package-managers-usage).
I was surprised to see it. I thought it could be beneficial with your CI/CD.

Cheers!

**Comment by phette23** [comment]
Oh interesting! I didn't know that, and reading the actions images repo is pretty informative. I'm not sure it fits into my CI/CD since poetry manages all that and it uses the local repo instead of PyPI but very good to know.

**Comment by klinga** [comment]
I was thinking about this step in your actions:
```yaml
            - uses: snok/install-poetry@v1
              with:
                version: 1.8.2
```
but I did not look too closely at this particular action, so I may be missing something.
Looks like installing poetry via pipx is something poetry [recommends](https://python-poetry.org/docs/#ci-recommendations) for CI. Just thought you also may find it interesting.

**Comment by phette23** [comment]
Switched to `pipx install poetry` in v1.0.4.
